// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `factory.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __factory_h__
#define __factory_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Factory
{

class DeviceAbs;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Factory::DeviceAbs>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Factory::DeviceAbs*);

class DeviceFactory;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Factory::DeviceFactory>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Factory::DeviceFactory*);

}

}

namespace Factory
{

class DeviceAbs;
bool operator==(const DeviceAbs&, const DeviceAbs&);
bool operator<(const DeviceAbs&, const DeviceAbs&);
::Ice::Object* upCast(::Factory::DeviceAbs*);
typedef ::IceInternal::Handle< ::Factory::DeviceAbs> DeviceAbsPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Factory::DeviceAbs> DeviceAbsPrx;
void __patch(DeviceAbsPtr&, const ::Ice::ObjectPtr&);

class DeviceFactory;
bool operator==(const DeviceFactory&, const DeviceFactory&);
bool operator<(const DeviceFactory&, const DeviceFactory&);
::Ice::Object* upCast(::Factory::DeviceFactory*);
typedef ::IceInternal::Handle< ::Factory::DeviceFactory> DeviceFactoryPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Factory::DeviceFactory> DeviceFactoryPrx;
void __patch(DeviceFactoryPtr&, const ::Ice::ObjectPtr&);

}

namespace Factory
{

typedef ::std::vector< ::std::string> TStringArray;

typedef ::std::vector< ::Ice::Double> TDoubleArray;

}

namespace Factory
{

class Callback_DeviceAbs_status_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DeviceAbs_status_Base> Callback_DeviceAbs_statusPtr;

class Callback_DeviceAbs_release_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DeviceAbs_release_Base> Callback_DeviceAbs_releasePtr;

class Callback_DeviceFactory_interfaces_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DeviceFactory_interfaces_Base> Callback_DeviceFactory_interfacesPtr;

class Callback_DeviceFactory_query_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DeviceFactory_query_Base> Callback_DeviceFactory_queryPtr;

}

namespace IceProxy
{

namespace Factory
{

class DeviceAbs : virtual public ::IceProxy::Ice::Object
{
public:

    ::std::string status()
    {
        return status(0);
    }
    ::std::string status(const ::Ice::Context& __ctx)
    {
        return status(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_status(const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_status(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_status(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_status(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_status(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_status(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_status(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_status(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_status(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Factory::DeviceAbsPrx __proxy = ::Factory::DeviceAbsPrx::uncheckedCast(__result->getProxy());
                ::std::string __ret;
                try
                {
                    __ret = __proxy->end_status(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_status(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_status()
    {
        return begin_status(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_status(const ::Ice::Context& __ctx)
    {
        return begin_status(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_status(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_status(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_status(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_status(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_status(const ::Factory::Callback_DeviceAbs_statusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_status(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_status(const ::Ice::Context& __ctx, const ::Factory::Callback_DeviceAbs_statusPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_status(&__ctx, __del, __cookie);
    }

    ::std::string end_status(const ::Ice::AsyncResultPtr&);
    
private:

    ::std::string status(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_status(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void release()
    {
        release(0);
    }
    void release(const ::Ice::Context& __ctx)
    {
        release(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_release(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_release(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_release(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_release(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_release(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_release(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_release(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_release(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_release()
    {
        return begin_release(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_release(const ::Ice::Context& __ctx)
    {
        return begin_release(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_release(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_release(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_release(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_release(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_release(const ::Factory::Callback_DeviceAbs_releasePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_release(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_release(const ::Ice::Context& __ctx, const ::Factory::Callback_DeviceAbs_releasePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_release(&__ctx, __del, __cookie);
    }

    void end_release(const ::Ice::AsyncResultPtr&);
    
private:

    void release(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_release(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_secure(bool __secure) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_twoway() const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_oneway() const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_batchOneway() const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_datagram() const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_batchDatagram() const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_compress(bool __compress) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_timeout(int __timeout) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceAbs> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<DeviceAbs*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class DeviceFactory : virtual public ::IceProxy::Ice::Object
{
public:

    ::Factory::TStringArray interfaces()
    {
        return interfaces(0);
    }
    ::Factory::TStringArray interfaces(const ::Ice::Context& __ctx)
    {
        return interfaces(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_interfaces(const ::IceInternal::Function<void (const ::Factory::TStringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_interfaces(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_interfaces(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_interfaces(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_interfaces(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Factory::TStringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_interfaces(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_interfaces(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_interfaces(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_interfaces(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Factory::TStringArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Factory::TStringArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
                ::Factory::TStringArray __ret;
                try
                {
                    __ret = __proxy->end_interfaces(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Factory::TStringArray&)> _response;
        };
        return begin_interfaces(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_interfaces()
    {
        return begin_interfaces(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_interfaces(const ::Ice::Context& __ctx)
    {
        return begin_interfaces(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_interfaces(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_interfaces(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_interfaces(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_interfaces(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_interfaces(const ::Factory::Callback_DeviceFactory_interfacesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_interfaces(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_interfaces(const ::Ice::Context& __ctx, const ::Factory::Callback_DeviceFactory_interfacesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_interfaces(&__ctx, __del, __cookie);
    }

    ::Factory::TStringArray end_interfaces(const ::Ice::AsyncResultPtr&);
    
private:

    ::Factory::TStringArray interfaces(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_interfaces(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Factory::DeviceAbsPrx query(const ::std::string& interfaceName)
    {
        return query(interfaceName, 0);
    }
    ::Factory::DeviceAbsPrx query(const ::std::string& interfaceName, const ::Ice::Context& __ctx)
    {
        return query(interfaceName, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& interfaceName, const ::IceInternal::Function<void (const ::Factory::DeviceAbsPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_query(interfaceName, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& interfaceName, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_query(interfaceName, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& interfaceName, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Factory::DeviceAbsPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_query(interfaceName, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_query(const ::std::string& interfaceName, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_query(interfaceName, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_query(const ::std::string& interfaceName, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Factory::DeviceAbsPrx&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::Factory::DeviceAbsPrx&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
                ::Factory::DeviceAbsPrx __ret;
                try
                {
                    __ret = __proxy->end_query(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::Factory::DeviceAbsPrx&)> _response;
        };
        return begin_query(interfaceName, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName)
    {
        return begin_query(interfaceName, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName, const ::Ice::Context& __ctx)
    {
        return begin_query(interfaceName, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(interfaceName, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(interfaceName, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName, const ::Factory::Callback_DeviceFactory_queryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(interfaceName, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_query(const ::std::string& interfaceName, const ::Ice::Context& __ctx, const ::Factory::Callback_DeviceFactory_queryPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_query(interfaceName, &__ctx, __del, __cookie);
    }

    ::Factory::DeviceAbsPrx end_query(const ::Ice::AsyncResultPtr&);
    
private:

    ::Factory::DeviceAbsPrx query(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_query(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_secure(bool __secure) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_twoway() const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_oneway() const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_batchOneway() const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_datagram() const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_batchDatagram() const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_compress(bool __compress) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_timeout(int __timeout) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<DeviceFactory> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<DeviceFactory*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Factory
{

class DeviceAbs : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::std::string status(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void release(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

class DeviceFactory : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Factory::TStringArray interfaces(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Factory::DeviceAbsPrx query(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Factory
{

class DeviceAbs : virtual public ::IceDelegate::Factory::DeviceAbs,
                  virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::std::string status(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void release(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class DeviceFactory : virtual public ::IceDelegate::Factory::DeviceFactory,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Factory::TStringArray interfaces(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Factory::DeviceAbsPrx query(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Factory
{

class DeviceAbs : virtual public ::IceDelegate::Factory::DeviceAbs,
                  virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::std::string status(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void release(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

class DeviceFactory : virtual public ::IceDelegate::Factory::DeviceFactory,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Factory::TStringArray interfaces(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Factory::DeviceAbsPrx query(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Factory
{

class DeviceAbs : virtual public ::Ice::Object
{
public:

    typedef DeviceAbsPrx ProxyType;
    typedef DeviceAbsPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::std::string status(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___status(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void release(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___release(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const DeviceAbs& l, const DeviceAbs& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const DeviceAbs& l, const DeviceAbs& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class DeviceFactory : virtual public ::Ice::Object
{
public:

    typedef DeviceFactoryPrx ProxyType;
    typedef DeviceFactoryPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Factory::TStringArray interfaces(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___interfaces(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Factory::DeviceAbsPrx query(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___query(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const DeviceFactory& l, const DeviceFactory& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const DeviceFactory& l, const DeviceFactory& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Factory
{

template<class T>
class CallbackNC_DeviceAbs_status : public Callback_DeviceAbs_status_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_DeviceAbs_status(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceAbsPrx __proxy = ::Factory::DeviceAbsPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_status(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_DeviceAbs_statusPtr
newCallback_DeviceAbs_status(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_status<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DeviceAbs_statusPtr
newCallback_DeviceAbs_status(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_status<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_DeviceAbs_status : public Callback_DeviceAbs_status_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_DeviceAbs_status(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceAbsPrx __proxy = ::Factory::DeviceAbsPrx::uncheckedCast(__result->getProxy());
        ::std::string __ret;
        try
        {
            __ret = __proxy->end_status(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_DeviceAbs_statusPtr
newCallback_DeviceAbs_status(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_status<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceAbs_statusPtr
newCallback_DeviceAbs_status(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_status<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_DeviceAbs_release : public Callback_DeviceAbs_release_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_DeviceAbs_release(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_release<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_release<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_release<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceAbs_release<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_DeviceAbs_release : public Callback_DeviceAbs_release_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_DeviceAbs_release(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_release<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_release<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_release<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceAbs_releasePtr
newCallback_DeviceAbs_release(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceAbs_release<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_DeviceFactory_interfaces : public Callback_DeviceFactory_interfaces_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Factory::TStringArray&);

    CallbackNC_DeviceFactory_interfaces(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
        ::Factory::TStringArray __ret;
        try
        {
            __ret = __proxy->end_interfaces(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_DeviceFactory_interfacesPtr
newCallback_DeviceFactory_interfaces(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Factory::TStringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceFactory_interfaces<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DeviceFactory_interfacesPtr
newCallback_DeviceFactory_interfaces(T* instance, void (T::*cb)(const ::Factory::TStringArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceFactory_interfaces<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_DeviceFactory_interfaces : public Callback_DeviceFactory_interfaces_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Factory::TStringArray&, const CT&);

    Callback_DeviceFactory_interfaces(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
        ::Factory::TStringArray __ret;
        try
        {
            __ret = __proxy->end_interfaces(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_DeviceFactory_interfacesPtr
newCallback_DeviceFactory_interfaces(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Factory::TStringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceFactory_interfaces<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceFactory_interfacesPtr
newCallback_DeviceFactory_interfaces(T* instance, void (T::*cb)(const ::Factory::TStringArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceFactory_interfaces<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_DeviceFactory_query : public Callback_DeviceFactory_query_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Factory::DeviceAbsPrx&);

    CallbackNC_DeviceFactory_query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
        ::Factory::DeviceAbsPrx __ret;
        try
        {
            __ret = __proxy->end_query(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_DeviceFactory_queryPtr
newCallback_DeviceFactory_query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Factory::DeviceAbsPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceFactory_query<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DeviceFactory_queryPtr
newCallback_DeviceFactory_query(T* instance, void (T::*cb)(const ::Factory::DeviceAbsPrx&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DeviceFactory_query<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_DeviceFactory_query : public Callback_DeviceFactory_query_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Factory::DeviceAbsPrx&, const CT&);

    Callback_DeviceFactory_query(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Factory::DeviceFactoryPrx __proxy = ::Factory::DeviceFactoryPrx::uncheckedCast(__result->getProxy());
        ::Factory::DeviceAbsPrx __ret;
        try
        {
            __ret = __proxy->end_query(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_DeviceFactory_queryPtr
newCallback_DeviceFactory_query(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Factory::DeviceAbsPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceFactory_query<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DeviceFactory_queryPtr
newCallback_DeviceFactory_query(T* instance, void (T::*cb)(const ::Factory::DeviceAbsPrx&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DeviceFactory_query<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
