// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `digitizer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <digitizer.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Device__Digitizer__instantValues_name = "instantValues";

const ::std::string __Device__Digitizer__setTrigEn_name = "setTrigEn";

const ::std::string __Device__Digitizer__values_name = "values";

}
::IceProxy::Ice::Object* ::IceProxy::Device::upCast(::IceProxy::Device::Digitizer* p) { return p; }

void
::IceProxy::Device::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Device::Digitizer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Device::Digitizer;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::Device::Digitizer::instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Device__Digitizer__instantValues_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Device__Digitizer__instantValues_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Device::Digitizer* __del = dynamic_cast< ::IceDelegate::Device::Digitizer*>(__delBase.get());
            return __del->instantValues(workV, workI, probeV, probeI, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_instantValues(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__instantValues_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__instantValues_name, __del, __cookie);
    try
    {
        __result->__prepare(__Device__Digitizer__instantValues_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::Device::Digitizer::end_instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__instantValues_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(workV);
        __is->read(workI);
        __is->read(probeV);
        __is->read(probeI);
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::Device::Digitizer::setTrigEn(bool en, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Device__Digitizer__setTrigEn_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Device__Digitizer__setTrigEn_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Device::Digitizer* __del = dynamic_cast< ::IceDelegate::Device::Digitizer*>(__delBase.get());
            return __del->setTrigEn(en, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_setTrigEn(bool en, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__setTrigEn_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__setTrigEn_name, __del, __cookie);
    try
    {
        __result->__prepare(__Device__Digitizer__setTrigEn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(en);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::Device::Digitizer::end_setTrigEn(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__setTrigEn_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::Device::Digitizer::values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __Device__Digitizer__values_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Device__Digitizer__values_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Device::Digitizer* __del = dynamic_cast< ::IceDelegate::Device::Digitizer*>(__delBase.get());
            return __del->values(workV, workI, probeV, probeI, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Device::Digitizer::begin_values(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Device__Digitizer__values_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Device__Digitizer__values_name, __del, __cookie);
    try
    {
        __result->__prepare(__Device__Digitizer__values_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::Device::Digitizer::end_values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Device__Digitizer__values_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(workV);
        __is->read(workI);
        __is->read(probeV);
        __is->read(probeI);
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::Device::Digitizer::ice_staticId()
{
    return ::Device::Digitizer::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Device::Digitizer::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Device::Digitizer);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Device::Digitizer::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Device::Digitizer);
}

::IceProxy::Ice::Object*
IceProxy::Device::Digitizer::__newInstance() const
{
    return new Digitizer;
}

bool
IceDelegateM::Device::Digitizer::instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Device__Digitizer__instantValues_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(workV);
        __is->read(workI);
        __is->read(probeV);
        __is->read(probeI);
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::Device::Digitizer::setTrigEn(bool en, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Device__Digitizer__setTrigEn_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(en);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::Device::Digitizer::values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Device__Digitizer__values_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(workV);
        __is->read(workI);
        __is->read(probeV);
        __is->read(probeI);
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::Device::Digitizer::instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, ::Ice::Double& __p_workV, ::Ice::Double& __p_workI, ::Ice::Double& __p_probeV, ::Ice::Double& __p_probeI, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_workV(__p_workV),
            _m_workI(__p_workI),
            _m_probeV(__p_probeV),
            _m_probeI(__p_probeI)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Device::Digitizer* servant = dynamic_cast< ::Device::Digitizer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->instantValues(_m_workV, _m_workI, _m_probeV, _m_probeI, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        ::Ice::Double& _m_workV;
        ::Ice::Double& _m_workI;
        ::Ice::Double& _m_probeV;
        ::Ice::Double& _m_probeI;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Device__Digitizer__instantValues_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, workV, workI, probeV, probeI, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::Device::Digitizer::setTrigEn(bool en, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, bool __p_en, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_en(__p_en)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Device::Digitizer* servant = dynamic_cast< ::Device::Digitizer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->setTrigEn(_m_en, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        bool _m_en;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Device__Digitizer__setTrigEn_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, en, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::Device::Digitizer::values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, ::Factory::TDoubleArray& __p_workV, ::Factory::TDoubleArray& __p_workI, ::Factory::TDoubleArray& __p_probeV, ::Factory::TDoubleArray& __p_probeI, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_workV(__p_workV),
            _m_workI(__p_workI),
            _m_probeV(__p_probeV),
            _m_probeI(__p_probeI)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Device::Digitizer* servant = dynamic_cast< ::Device::Digitizer*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->values(_m_workV, _m_workI, _m_probeV, _m_probeI, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        ::Factory::TDoubleArray& _m_workV;
        ::Factory::TDoubleArray& _m_workI;
        ::Factory::TDoubleArray& _m_probeV;
        ::Factory::TDoubleArray& _m_probeI;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Device__Digitizer__values_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, workV, workI, probeV, probeI, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* Device::upCast(::Device::Digitizer* p) { return p; }

namespace
{
const ::std::string __Device__Digitizer_ids[3] =
{
    "::Device::Digitizer",
    "::Factory::DeviceAbs",
    "::Ice::Object"
};

}

bool
Device::Digitizer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Device__Digitizer_ids, __Device__Digitizer_ids + 3, _s);
}

::std::vector< ::std::string>
Device::Digitizer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Device__Digitizer_ids[0], &__Device__Digitizer_ids[3]);
}

const ::std::string&
Device::Digitizer::ice_id(const ::Ice::Current&) const
{
    return __Device__Digitizer_ids[0];
}

const ::std::string&
Device::Digitizer::ice_staticId()
{
    return __Device__Digitizer_ids[0];
}

::Ice::DispatchStatus
Device::Digitizer::___instantValues(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Double workV;
    ::Ice::Double workI;
    ::Ice::Double probeV;
    ::Ice::Double probeI;
    bool __ret = instantValues(workV, workI, probeV, probeI, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(workV);
    __os->write(workI);
    __os->write(probeV);
    __os->write(probeI);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Device::Digitizer::___setTrigEn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    bool en;
    __is->read(en);
    __inS.endReadParams();
    bool __ret = setTrigEn(en, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Device::Digitizer::___values(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Factory::TDoubleArray workV;
    ::Factory::TDoubleArray workI;
    ::Factory::TDoubleArray probeV;
    ::Factory::TDoubleArray probeI;
    bool __ret = values(workV, workI, probeV, probeI, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(workV);
    __os->write(workI);
    __os->write(probeV);
    __os->write(probeI);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Device__Digitizer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "instantValues",
    "release",
    "setTrigEn",
    "status",
    "values"
};

}

::Ice::DispatchStatus
Device::Digitizer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Device__Digitizer_all, __Device__Digitizer_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Device__Digitizer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___instantValues(in, current);
        }
        case 5:
        {
            return ___release(in, current);
        }
        case 6:
        {
            return ___setTrigEn(in, current);
        }
        case 7:
        {
            return ___status(in, current);
        }
        case 8:
        {
            return ___values(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Device::Digitizer::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Device::Digitizer::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Device::__patch(DigitizerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Device::DigitizerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Device::Digitizer::ice_staticId(), v);
    }
}
