// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `digitizer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __digitizer_h__
#define __digitizer_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <factory.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Device
{

class Digitizer;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Device::Digitizer>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Device::Digitizer*);

}

}

namespace Device
{

class Digitizer;
bool operator==(const Digitizer&, const Digitizer&);
bool operator<(const Digitizer&, const Digitizer&);
::Ice::Object* upCast(::Device::Digitizer*);
typedef ::IceInternal::Handle< ::Device::Digitizer> DigitizerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Device::Digitizer> DigitizerPrx;
void __patch(DigitizerPtr&, const ::Ice::ObjectPtr&);

}

namespace Device
{

class Callback_Digitizer_instantValues_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Digitizer_instantValues_Base> Callback_Digitizer_instantValuesPtr;

class Callback_Digitizer_setTrigEn_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Digitizer_setTrigEn_Base> Callback_Digitizer_setTrigEnPtr;

class Callback_Digitizer_values_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Digitizer_values_Base> Callback_Digitizer_valuesPtr;

}

namespace IceProxy
{

namespace Device
{

class Digitizer : virtual public ::IceProxy::Factory::DeviceAbs
{
public:

    bool instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI)
    {
        return instantValues(workV, workI, probeV, probeI, 0);
    }
    bool instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::Context& __ctx)
    {
        return instantValues(workV, workI, probeV, probeI, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_instantValues(const ::IceInternal::Function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_instantValues(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_instantValues(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_instantValues(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_instantValues(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_instantValues(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_instantValues(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_instantValues(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_instantValues(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Double workV;
                ::Ice::Double workI;
                ::Ice::Double probeV;
                ::Ice::Double probeI;
                bool __ret;
                try
                {
                    __ret = __proxy->end_instantValues(workV, workI, probeV, probeI, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret, workV, workI, probeV, probeI);
                }
            }
        
        private:
            
            ::std::function<void (bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double)> _response;
        };
        return begin_instantValues(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_instantValues()
    {
        return begin_instantValues(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_instantValues(const ::Ice::Context& __ctx)
    {
        return begin_instantValues(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_instantValues(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_instantValues(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_instantValues(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_instantValues(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_instantValues(const ::Device::Callback_Digitizer_instantValuesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_instantValues(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_instantValues(const ::Ice::Context& __ctx, const ::Device::Callback_Digitizer_instantValuesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_instantValues(&__ctx, __del, __cookie);
    }

    bool end_instantValues(::Ice::Double& workV, ::Ice::Double& workI, ::Ice::Double& probeV, ::Ice::Double& probeI, const ::Ice::AsyncResultPtr&);
    
private:

    bool instantValues(::Ice::Double&, ::Ice::Double&, ::Ice::Double&, ::Ice::Double&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_instantValues(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool setTrigEn(bool en)
    {
        return setTrigEn(en, 0);
    }
    bool setTrigEn(bool en, const ::Ice::Context& __ctx)
    {
        return setTrigEn(en, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_setTrigEn(bool en, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_setTrigEn(en, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_setTrigEn(bool en, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setTrigEn(en, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_setTrigEn(bool en, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_setTrigEn(en, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_setTrigEn(bool en, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_setTrigEn(en, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_setTrigEn(bool en, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_setTrigEn(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_setTrigEn(en, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en)
    {
        return begin_setTrigEn(en, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en, const ::Ice::Context& __ctx)
    {
        return begin_setTrigEn(en, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setTrigEn(en, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setTrigEn(en, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en, const ::Device::Callback_Digitizer_setTrigEnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setTrigEn(en, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setTrigEn(bool en, const ::Ice::Context& __ctx, const ::Device::Callback_Digitizer_setTrigEnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setTrigEn(en, &__ctx, __del, __cookie);
    }

    bool end_setTrigEn(const ::Ice::AsyncResultPtr&);
    
private:

    bool setTrigEn(bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setTrigEn(bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI)
    {
        return values(workV, workI, probeV, probeI, 0);
    }
    bool values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::Context& __ctx)
    {
        return values(workV, workI, probeV, probeI, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_values(const ::IceInternal::Function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_values(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_values(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_values(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_values(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_values(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_values(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_values(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_values(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
                ::Factory::TDoubleArray workV;
                ::Factory::TDoubleArray workI;
                ::Factory::TDoubleArray probeV;
                ::Factory::TDoubleArray probeI;
                bool __ret;
                try
                {
                    __ret = __proxy->end_values(workV, workI, probeV, probeI, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret, workV, workI, probeV, probeI);
                }
            }
        
        private:
            
            ::std::function<void (bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&)> _response;
        };
        return begin_values(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_values()
    {
        return begin_values(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_values(const ::Ice::Context& __ctx)
    {
        return begin_values(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_values(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_values(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_values(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_values(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_values(const ::Device::Callback_Digitizer_valuesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_values(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_values(const ::Ice::Context& __ctx, const ::Device::Callback_Digitizer_valuesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_values(&__ctx, __del, __cookie);
    }

    bool end_values(::Factory::TDoubleArray& workV, ::Factory::TDoubleArray& workI, ::Factory::TDoubleArray& probeV, ::Factory::TDoubleArray& probeI, const ::Ice::AsyncResultPtr&);
    
private:

    bool values(::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_values(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Digitizer> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_secure(bool __secure) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_twoway() const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_oneway() const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_batchOneway() const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_datagram() const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_batchDatagram() const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_compress(bool __compress) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Digitizer> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Digitizer*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Device
{

class Digitizer : virtual public ::IceDelegate::Factory::DeviceAbs
{
public:

    virtual bool instantValues(::Ice::Double&, ::Ice::Double&, ::Ice::Double&, ::Ice::Double&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool setTrigEn(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool values(::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Device
{

class Digitizer : virtual public ::IceDelegate::Device::Digitizer,
                  virtual public ::IceDelegateM::Factory::DeviceAbs
{
public:

    virtual bool instantValues(::Ice::Double&, ::Ice::Double&, ::Ice::Double&, ::Ice::Double&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool setTrigEn(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool values(::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Device
{

class Digitizer : virtual public ::IceDelegate::Device::Digitizer,
                  virtual public ::IceDelegateD::Factory::DeviceAbs
{
public:

    virtual bool instantValues(::Ice::Double&, ::Ice::Double&, ::Ice::Double&, ::Ice::Double&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool setTrigEn(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool values(::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Device
{

class Digitizer : virtual public ::Factory::DeviceAbs
{
public:

    typedef DigitizerPrx ProxyType;
    typedef DigitizerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual bool instantValues(::Ice::Double&, ::Ice::Double&, ::Ice::Double&, ::Ice::Double&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___instantValues(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool setTrigEn(bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setTrigEn(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool values(::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, ::Factory::TDoubleArray&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___values(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Digitizer& l, const Digitizer& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Digitizer& l, const Digitizer& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Device
{

template<class T>
class CallbackNC_Digitizer_instantValues : public Callback_Digitizer_instantValues_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double);

    CallbackNC_Digitizer_instantValues(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Double workV;
        ::Ice::Double workI;
        ::Ice::Double probeV;
        ::Ice::Double probeI;
        bool __ret;
        try
        {
            __ret = __proxy->end_instantValues(workV, workI, probeV, probeI, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, workV, workI, probeV, probeI);
        }
    }

    Response response;
};

template<class T> Callback_Digitizer_instantValuesPtr
newCallback_Digitizer_instantValues(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_instantValues<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Digitizer_instantValuesPtr
newCallback_Digitizer_instantValues(T* instance, void (T::*cb)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_instantValues<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Digitizer_instantValues : public Callback_Digitizer_instantValues_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double, const CT&);

    Callback_Digitizer_instantValues(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Double workV;
        ::Ice::Double workI;
        ::Ice::Double probeV;
        ::Ice::Double probeI;
        bool __ret;
        try
        {
            __ret = __proxy->end_instantValues(workV, workI, probeV, probeI, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, workV, workI, probeV, probeI, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Digitizer_instantValuesPtr
newCallback_Digitizer_instantValues(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_instantValues<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Digitizer_instantValuesPtr
newCallback_Digitizer_instantValues(T* instance, void (T::*cb)(bool, ::Ice::Double, ::Ice::Double, ::Ice::Double, ::Ice::Double, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_instantValues<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Digitizer_setTrigEn : public Callback_Digitizer_setTrigEn_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_Digitizer_setTrigEn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_setTrigEn(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Digitizer_setTrigEnPtr
newCallback_Digitizer_setTrigEn(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_setTrigEn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Digitizer_setTrigEnPtr
newCallback_Digitizer_setTrigEn(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_setTrigEn<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Digitizer_setTrigEn : public Callback_Digitizer_setTrigEn_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_Digitizer_setTrigEn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_setTrigEn(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Digitizer_setTrigEnPtr
newCallback_Digitizer_setTrigEn(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_setTrigEn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Digitizer_setTrigEnPtr
newCallback_Digitizer_setTrigEn(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_setTrigEn<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Digitizer_values : public Callback_Digitizer_values_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&);

    CallbackNC_Digitizer_values(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        ::Factory::TDoubleArray workV;
        ::Factory::TDoubleArray workI;
        ::Factory::TDoubleArray probeV;
        ::Factory::TDoubleArray probeI;
        bool __ret;
        try
        {
            __ret = __proxy->end_values(workV, workI, probeV, probeI, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret, workV, workI, probeV, probeI);
        }
    }

    Response response;
};

template<class T> Callback_Digitizer_valuesPtr
newCallback_Digitizer_values(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_values<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Digitizer_valuesPtr
newCallback_Digitizer_values(T* instance, void (T::*cb)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Digitizer_values<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Digitizer_values : public Callback_Digitizer_values_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const CT&);

    Callback_Digitizer_values(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Device::DigitizerPrx __proxy = ::Device::DigitizerPrx::uncheckedCast(__result->getProxy());
        ::Factory::TDoubleArray workV;
        ::Factory::TDoubleArray workI;
        ::Factory::TDoubleArray probeV;
        ::Factory::TDoubleArray probeI;
        bool __ret;
        try
        {
            __ret = __proxy->end_values(workV, workI, probeV, probeI, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, workV, workI, probeV, probeI, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Digitizer_valuesPtr
newCallback_Digitizer_values(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_values<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Digitizer_valuesPtr
newCallback_Digitizer_values(T* instance, void (T::*cb)(bool, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const ::Factory::TDoubleArray&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Digitizer_values<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
